# test

MySQL:
  host: "localhost"
  port: 3306
  database: "prophecymining"
  username: "root"
  password: ""

lang:
  only_players: "&cThis command can only be accessed by players!"
  levelup_message:
    - "&8&m----------------------------"
    - ""
    - "&eCongrats, %player%, you have leveled up"
    - "&eto level %level%!"
    - ""
    - "&8&m----------------------------"
  actionbar: "&3+%amount% XP (%current%/%total%)"
  coins_help_message:
    - "&eThe following commands are available:"
    - "&8/&ecoins get <player>"
    - "&8/&ecoins set <player> <amount>"
    - "&8/&ecoins add <player> <amount>"
    - "&8/&ecoins take <player> <amount>"
  region_help_message:
    - "&eThe following commands are available:"
    - "&8/&esbregion create <regionName> <type>"
    - "&8/&esbregion delete <regionName>"
    - "&8/&esbregion list"
  shop_item_sell_name: "&6* &fSell &e%amount% &fof %itemName%"
  shop_item_buy_name: "&6* &fBuy &e%amount% &fof %itemName%"
  shop_item_buy_lore:
    - ""
    - "&fBy &6Right-Clicking &fon this item"
    - "&fyou will attempt purchasing &ex%amount% &fof"
    - "%itemName%&f."
    - ""
    - "&6* Price: &e%price%"
  shop_item_sell_lore:
    - ""
    - "&fBy &6Right-Clicking on this item"
    - "&fyou will sell &ex%amount% &fof"
    - "%itemName% &ffor &e%price%&f."
  coins_specify_player: "&cYou need to specify a player to perform a lookup for!"
  coins_specify_amount: "&cYou need to specify an amount of coins!"
  coins_specify_valid_amount: "&cYou need to specify a &nVALID&r&c amount of coins! (NUMBERS)"
  target_does_not_exist: "&cThis player does not exist!"
  display_coins: "&e%player% has %amount% coins."
  add_coins: "&eYou have added %amount% coins to %player%'s balance!"
  remove_coins: "&eYou have removed %amount% coins from %player%'s balance!"
  set_coins: "&eYou have set %player%'s coins to: %amount%"
  coins_subtracted: "&e%amount% coins have been subtracted from your balance."
  coins_added: "&e%amount% coins have been added to your balance."
  coins_removed: "&e%amount% coins have been subtracted from your balance."
  command_not_found: "&cThis command doesn't exist! Please try again."
  no_permission: "&cYou don't have sufficient permissions to run this command!"
  rare_drop: "&6&lRARE DROP! &eYou've received a: %dropName%"
  rare_drop_coins: "&a&lDROP! &eYou've received %amount% Coins!"
  rareitemshop_title: "&6&lRARE ITEM SHOP"
  buy_text: "&6* &fBuy for: &e%price%"
  sell_text: "&6* &fSell for: &e%price%"
  buy_message: "&6&lSHOP - &fYou have bought &e%amount%x&r %itemName%(s) &ffor &e%price%&f."
  sell_message: "&6&lSHOP - &fYou have sold &e%amount%x&r %itemName%(s) &ffor &e%price%&f."
  not_enough_coins: "&cYou don't have enough coins to perform this transaction!"
  not_enough_items: "&cYou don't have any items of this type in your inventory!"
  close_menu: "&cGo Back"
  no_match: "&c(No items matching found!)"
  enchantment_shop_title: "&6&lENCHANTMENT SHOP"
  require_hold_pickaxe: "&cYou have to hold a pickaxe in order to access the Enchanting Menu!"
  max_level: "&cYou have already applied this Enchantment up to the maximum level!"
  not_enough_money: "&cNOT ENOUGH MONEY"
  inventory_full: "&cYour inventory is full!"
  specify_name: "&cSpecify a region name!"
  specify_type: "&cSpecify a region type!"
  type_invalid: "&cNo type matching %arg% was found! Please try again."
  name_already_exists: "&cA region named %name% already exists!"
  region_not_found: "No region named %name% was found while attempting lookup!"
  need_selection_first: "&cPlease, make a WorldEdit selection before utilizing this command!"
  incomplete_region: "&cPlease, select both parts of the region before utilizing this command!"
  region_created: "&6&lREGION - &eSuccessfully created a new region named: %name%"
  region_removed: "&6&lREGION - &eSuccessfully removed a region named: %name%"
  displaying_regions: "&6Displaying all valid regions... &7&o(This process might take a while)"
  region_format: "&6(*) &8- &e%regionName% &7(%ores% | %stones%) &e- &6Type: &e%type% &8/ &6"

region:
  time: 2 # Set in seconds.

enchantments:
  luck_bonus_chance_per_level: 5
  name: "&6%enchantName%"
  buy: "&fApply this enchantment for &6%price%&f!"
  autopickup:
    price: 1250
    lore:
      - "&7Picks up items!"
  autosell:
    price: 2500
    lore:
      - "&7Automatically sells items!"
  luck:
    price: 500
    lore:
      - "&7Increases rare drop chances."
  drill:
    price: 1000
    lore:
      - "&7Digs in a 3x3 cube."
  fortune:
    price: 1500
    lore:
      - "&7Vanilla Minecraft fortune."
      - "&6&lTESTING"
  efficiency:
    price: 2500
    lore:
      - "&7Vanilla Minecraft efficiency"
      - "&eomega"
  unbreaking:
    price: 750
    lore:
      - "&7Efficiency"
  mending:
    price: 5000
    lore:
      - "&7Mending!"

xp:
  coal:
    start: 5
    end: 13
  iron:
    start: 6
    end: 14
  gold:
    start: 8
    end: 17
  emerald:
    start: 10
    end: 20
  lapis:
    start: 12
    end: 24
  redstone:
    start: 15
    end: 30
  diamond:
    start: 16
    end: 32

coins:
  drop_chance: 10
  lower_bound: 5
  upper_bound: 25

drops:
  amethyst:
    name: "&5Amethyst"
    material: "DIAMOND"
    chance: 10
    buy_price: 1500
    sell_price: 1000
    lore:
      - "&7This is an Amethyst!"
  ruby:
    name: "&cRuby"
    chance: 5
    material: "REDSTONE"
    buy_price: 1250
    sell_price: 750
    lore:
      - "&7This is a Ruby!"
  gemstone:
    name: "&aGemstone"
    chance: 3
    material: "EMERALD"
    buy_price: 1000
    sell_price: 500
    lore:
      - "&7This is an Emerald!"

rewards:
  level_2:
    command: "give %player% diamond 20"


  # Milestone configuration
leveling:
  milestones:
    # Set this to enabled only if you want
    # the amount of needed XP per level to
    # increase with a set amount (i.e: Level 1
    # is 2500, Level 2 is 2500*2, Level 3 is 2500*3 etc.)
    increment:
      enabled: false
      increment_value: 2500
    # Change these as you wish.
    # These are set to match Hypixel Skyblock's level
    # requirements. These are global!
    level_1: 50
    level_2: 125
    level_3: 200
    level_4: 300
    level_5: 500
    level_6: 750
    level_7: 1000
    level_8: 1500
    level_9: 2000
    level_10: 3500
    level_11: 5000
    level_12: 7500
    level_13: 10000
    level_14: 15000
    level_15: 20000
    level_16: 30000
    level_17: 50000
    level_18: 75000
    level_19: 100000
    level_20: 200000
    level_21: 300000
    level_22: 400000
    level_23: 500000
    level_24: 600000
    level_25: 700000
    level_26: 800000
    level_27: 900000
    level_28: 1000000
    level_29: 1100000
    level_30: 1200000
    level_31: 1300000
    level_32: 1400000
    level_33: 1500000
    level_34: 1600000
    level_35: 1700000
    level_36: 1800000
    level_37: 1900000
    level_38: 2000000
    level_39: 2100000
    level_40: 2200000
    level_41: 2300000
    level_42: 2400000
    level_43: 2500000
    level_44: 2600000
    level_45: 2750000
    level_46: 2900000
    level_47: 3100000
    level_48: 3400000
    level_49: 3700000
    level_50: 4000000