main: by.thmihnea.prophecymining.ProphecyMining
author: thmihnea
version: 1.0.1
description: Mining plugin made for ProphecySB
name: ProphecyMining

api-version: 1.13

depend:
  - SmartInvs
  - ShopGUIPlus
  - Vault
  - PlaceholderAPI

commands:
  coins:
    description: Coins manipulation command for Prophecy Skyblock.
  rareitemshop:
    description: Opens up the Rare Item shop menu.
  enchanter:
    description: Opens up the Enchanting menu.